services:
  stock-report:
    build: .
    container_name: stock_report
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.tmp:/app/.tmp
    environment:
      - TZ=Asia/Seoul
